### ISSUE TITLE
Really loves your paper! A small question about uncertainty to ask.

### ISSUE THREAD

**Issue by synsin0** [h2xlab/InfDriver#1]
Thanks for your great work! I really loves your paper. Hope for your open-sourcing and I'll have a try if you are kind to open-source it.

I'd like to raise a question of uncertainty estimation. I read the paper and finds that the memory selection is based on uncertainty. The uncertainty is calculated with ensemble of teacher model ( which I understand is like an odometry task but not a driving policy prediction task), so is this uncertainty related to the student driving policy network? Or is there an assumption that if the ego motion estimation between future frames is highly uncertain, it will be a difficult case for driving policy network?

**Comment by leilai125** [comment]
Hi, thank you for your interest in our work. Apologies for the delayed response. I hope this clarifies your questions. Regarding your first question, the uncertainty estimation is not related to the student driving policy network itself but rather to the waypoints' pseudo-labels used during the student policy training. For your second question, we did not explicitly clarify this assumption because the connection is quite intuitive: uncertainty is derived from the disagreement in VO predictions, waypoints are recovered from the VO-predicted pose, and typically, scenarios like making a turn or encountering noisy images lead to high uncertainty in VO predictions, which are also challenging cases for driving tasks.

**Comment by synsin0** [comment]
Get your ideas! Thanks for the answer.
